### ISSUE TITLE
Seems not to summarize anything

### ISSUE THREAD

**Issue by houmie** [vgel/summarize.py#10]
I have run it as  ```./summarize.py "http://www.bbc.co.uk/news/world-asia-30869019"```
but the content is almost exactly the same as original.  There seem to be no summary taken place at all.

Am I doing something wrong?

**Comment by Rotten194** [comment]
It's a limitation of the simplistic algorithm the library uses right now. If you look at the paragraphs, the vast majority of them are only one sentence long. Multi-sentence paragraphs are summarized to their main sentence, but these micro-paragraphs aren't. I'd question the BBC's weird stylistic choice there, but programming-wise, the easiest fix would be to have an option to further summarize paragraphs to a set number. I'm pretty busy with other projects at the moment, but if you'd like to write a pull request I'd be happy to merge it.
