### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by steoo** [vgel/summarize.py#14]
Is there a way to set a language different than english?

**Comment by vgel** [comment]
No. That'd be a nice feature, but I don't have the time to add it right now.

**Comment by steoo** [comment]
No problem. I'm new to Python and NLTK but I can commit myself to do something like that. If you can give me some hint to understand how to implement other languages I can help.
As I read the code implementing another language means using an Italian tokenizer (e.g.) but I have to figure out how to use a different tokenizer than the english one
